services:
  - type: web
    name: qr-redirector
    runtime: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
